#!/bin/bash
# Create a light self-contained web gallery from the images inside the target dir. 

_lib_dir="$(pwd)/lib"
_html_template_header="$(<"template-header.html")"
_html_template_footer="$(<"template-footer.html")"

cd "$1" || exit;

mapfile -t pics < <(\
                   fd -i -uuu \
                   '^.*\.(jpg|JPG|jpeg|JPEG|png|PNG|webp|WEBP)$' \
                   --exclude "lib/" \
                   )

_html="$_html_template_header"

for file in "${pics[@]}"; do
  _html+="\n   <a href='"${file}"' data-sub-html=''><img class='card-img' src='${file}' ></a>"
done

_html+="$_html_template_footer"

printf "$_html" > index.html

cp -R "$_lib_dir" .
